### ISSUE TITLE
Fetch-> fatal: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by matheusssilva** [gitkraken/vscode-gitlens#1027]
- GitLens Version: 10.2.1
- VSCode Version: 1.45.0
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1 - Clone any repository
2 - Click in "Fatch Repositories Button".

![gitlens_fetch_error](https://user-images.githubusercontent.com/7414956/81565224-6433f100-936f-11ea-816c-f4a7fc169d22.png)

Output debug:

```
[2020-05-11 13:04:31:366] [9f] GitService.getOrderedRepositories
[2020-05-11 13:04:31:366] [a0] GitService.getRepositories
[2020-05-11 13:04:31:367] [a0] GitService.getRepositories completed • 0 ms
[2020-05-11 13:04:31:367] [9f] GitService.getOrderedRepositories completed • 0 ms
[2020-05-11 13:04:31:368] [a2] GitService.getOrderedRepositories
[2020-05-11 13:04:31:368] [a3] GitService.getRepositories
[2020-05-11 13:04:31:368] [a3] GitService.getRepositories completed • 0 ms
[2020-05-11 13:04:31:369] [a2] GitService.getOrderedRepositories completed • 0 ms
[2020-05-11 13:04:31:369] [a4] GitService.fetchAll — e=OculiNuboWeb, t={"all":false,"prune":false}
[2020-05-11 13:04:31:369] [a5] Repository(/home/matheus/megasync/programstudio/oculinuboweb/).fetch — {"all":false,"prune":false}
[2020-05-11 13:04:31:374] ChildProcess.exithandler
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch
fatal: could not read Username for 'https://github.com': No such device or address

[2020-05-11 13:04:31:374] ShowMessage(error, 'Unable to fetch repository. See output channel for more details', undefined, null)
[2020-05-11 13:04:31:378] [a4] GitService.fetchAll completed • 8 ms
[2020-05-11 13:04:31:378] [a5] Repository(/home/matheus/megasync/programstudio/oculinuboweb/).fetch completed • 9 ms
[2020-05-11 13:04:31:378] [a1] GitCommandsCommand.execute completed
[2020-05-11 13:04:43:349] ShowMessage(error, 'Unable to fetch repository. See output channel for more details', undefined, null) returned Open Output Channel
[2020-05-11 13:04:43:866] [a6] RepositoriesNode.onActiveEditorChanged
[2020-05-11 13:04:43:866] [a6] RepositoriesNode.onActiveEditorChanged completed • 0 ms
```

**Comment by sanmai-NL** [comment]
Whereas the basic VS Code Git extension asks for the password in the GUI, and does not ask it if it is loaded into the credential helper, GitLens refuses to do either.

**Comment by r4395250** [comment]
Hi, 

I've the same issue 

GitLens Version: 10.2.1
VSCode Version: 1.45.1 (user setup)
OS Version: Windows 10 Enterprise 1809

Steps to Reproduce:

1 - Clone any repository
2 - Click in "Fetch Repositories" button.

Output debug:
`[2020-06-09 07:21:46:485] ChildProcess.exithandler
Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false fetch origin
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Password for 'https://myusername@PrivateRemoteGitRepo.com': No such file or directory`

**Comment by AurimasAnskaitis** [comment]
Hi, pretty sure this is not potential bug. I experience it for 4 months maybe. Sorry, no new information, writing this to bump the thread.

**Comment by pm-at** [comment]
Same for me
```
[2020-11-24 07:34:37:699] /home/frappe/.vscode-server/extensions/eamodio.gitlens-11.0.1/dist/gitlens.js:2:817381
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch
fatal: could not read Username for 'https://github.com': No such device or address
```

**Comment by manie204** [comment]
Same issue on

* GitLens Version: 11.0.6
* VSCode Version: 1.51.1 (user setup)
* OS Version: Windows_NT x64 10.0.19041

I'm working on a remote server via [remote ssh](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) and the git remote sits on a machine in that same network on a mounted file system.
GitLens log:

```
[2020-12-01 16:36:39:610] /fs/home/user/.vscode-server/extensions/eamodio.gitlens-11.0.6/dist/gitlens.js:2:822425
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch
fatal: could not read Username for 'https://remote-repo.com': No such device or address
```

**Comment by Nicryc** [comment]
I'm having the exact same issue when cloning a project on Linux with HTTPS :

- GitLens version: 11.1.3
- VSCode version: 1.52.1
- OS Version: Linux Fedora 32 x86_64

My project is hosted on a private instance of Gitlab that can be accessible from anywhere and where I have access rights. However this same project can be fetched from VSCode on Windows, from VSCode on Linux when it has been cloned using SSH and from the Linux terminal (without VSCode).

```
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch
fatal: could not read Username for 'https://gitlab.remoterepo.com': No such device or address
```

**Comment by aswyatt** [comment]
I'm having the same issue, running VS Code via SSH remote. I have not problem on local machine, or on remote machine when I select pull, issue occurs when I fetch.

> [2021-02-11 17:23:15:061] /home/pi/.vscode-server/extensions/eamodio.gitlens-11.2.1/dist/gitlens.js:2:888662
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin SeaBreeze
fatal: could not read Username for 'https://github.com': No such device or address

**Comment by dpkkdn** [comment]
I had the same issue and solved it by changing the origin url as suggested here [https://stackoverflow.com/questions/22147574/fatal-could-not-read-username-for-https-github-com-no-such-file-or-directo#comment38938891_22852314](https://stackoverflow.com/questions/22147574/fatal-could-not-read-username-for-https-github-com-no-such-file-or-directo#comment38938891_22852314)

**Comment by hans2520** [comment]
This has happened to me after my primary SSH key has changed. Looking into a fix.

**Comment by eamodio** [comment]
Can anyone still reproduce this on the latest GitLens version 11.3 or later (or the current insiders version)?

**Comment by manie204** [comment]
I cannot reproduce this issue any more on GitLens 11.4.1. Thanks for taking care of it.

**Comment by astrackomni** [comment]
Hi!
GitLens Version: 11.4.1
VSCode Version: 1.55.2 (user setup)
OS Version: Windows 10 Pro Build: 19042.928

I use the VSCode on windows, the code runs in a WSL2 docker image.

In VSCode->WSL2->Docker->terminal, the
 `/usr/bin/git -c core.quotepath=false -c color.ui=false fetch`
 command works but GitLens fetch returns the same error:
```
[2021-04-17 11:31:09:640] [/home/user/work/repos/some_folder] Git Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch • could not read Username for 'https://github.com': No such device or address • 1486 ms 
[2021-04-17 11:31:09:642] /home/user/.vscode-server/extensions/eamodio.gitlens-11.4.1/dist/gitlens.js:53:36614
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch
fatal: could not read Username for 'https://github.com': No such device or address
```

Should I reinstall/reinitialize something?

best
Ákos

**Comment by eamodio** [comment]
I would be great if anyone who can reproduce this could try to debug it. I haven't been able to see this in action. Sorry.

**Comment by nirodaonline** [comment]
Hi and thanks for the support.

I'm having this issue when working on remote - ssh extension:

- Local: Windows 10
- Remote: Debian 10 server 
- VSCode 1.57.1
- GitLens 11.5.1

I can push and I can pull - it prompts for user and pass.
But when i try to fetch from the GitLens Remotes View it doesn't prompt and I get the same error:

```
[2021-06-21 11:18:13:306] Git Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin develop • could not read Username for 'https://bitbucket.example.org': No such device or address • 5155 ms 
[2021-06-21 11:18:13:307] /home/almeidam/.vscode-server/extensions/eamodio.gitlens-11.5.1/dist/gitlens.js:55:36671
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin develop
fatal: could not read Username for 'https://bitbucket.example.org': No such device or address
```

I'm glad to debug it further, but not sure how to do it.

**Comment by scaomath** [comment]
I encountered this bug a while ago (VSCode default git interface is fine, but GitLens fetch will invoke this bug), today I finally solved it by a simple
```bash
git config credential.helper store
```
before an add-commit-push. Then, this problem is solved for GitLens.

**Comment by nirodaonline** [comment]
> I encountered this bug a while ago (VSCode default git interface is fine, but GitLens fetch will invoke this bug), today I finally solved it by a simple
> 
> ```shell
> git config credential.helper store
> ```

This solves it by storing your git credentials on disk. But it's a workaround, it doesn't actually address the problem.

**Comment by ccossou** [comment]
I also have this bug on linux with:
GitLens - Git Supercharged v11.6.0
VS Code
Version : 1.58.2
Commit : c3f126316369cd610563c75b1b1725e0679adfb3
Date : 2021-07-14T22:30:16.440Z
Electron : 12.0.13
Chrome : 89.0.4389.128
Node.js : 14.16.0
V8 : 8.9.255.25-electron.0
OS : Linux x64 5.4.0-80-generic

When trying a fetch, I have the same info stated above.
```bash
[2021-07-30 13:11:45:151] [/local/home/ccossou/CLionProjects/yam_stat] Git Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin master • could not read Username for 'https://github.com': No such device or address • 186 ms 
[2021-07-30 13:11:45:151] /local/home/ccossou/.vscode/extensions/eamodio.gitlens-11.6.0/dist/gitlens.js:55:36633
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin master
fatal: could not read Username for 'https://github.com': No such device or address
```
If I can help, tell me what command to run, or what log to copy here. 

I removed the OAuth on github.com, but it doesn't even ask for my login. I logged in manually in VS code, gitlens is reinstalled and can access this account, but don't ask for it it seems.

**Comment by jhoogstraat** [comment]
I am having the exact same issue on my linux. I can use git from the terminal just fine however.
It happened right after changing the remote's url from the terminal, because I renamed the repo on github.

**Comment by jg572h** [comment]
I am getting this error, too.  This formerly worked fine, but I had to change the origin from ```git@<foo>``` to ```https://<foo>``` due to internal server issues.  Ever since then, I am not able to fetch with GitLens.  Doing so from the command-line works fine.  I tried uninstalling GitLens and reinstalling, as per a previous post, but that did not help.

Here's the error I see:
```
[2021-08-17 14:38:52:872] [/home/username/myproj] Git Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch • could not read Username for 'https://local.gitlab.net': No such device or address • 121 ms 
[2021-08-17 14:38:52:873] /home/username/.vscode-server/extensions/eamodio.gitlens-11.6.0/dist/gitlens.js:55:36633
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch
fatal: could not read Username for 'https://local.gitlab.net': No such device or address
```

**Comment by peterswords** [comment]
I also had this problem with GitLens on Windows + WSL2 (I running my workspace in a Docker container, but I don't think that makes any difference).

I went for the '`git config credential.helper store`' fix and this worked. I believe that [Git Credential Manager Core](https://github.com/microsoft/Git-Credential-Manager-Core) is part of WSL2, so the username/password is not stored unencrypted on disk. Certainly when I check the contents of `~/.git-credentials` it _looks_ encrypted.

**Comment by jamesSampica** [comment]
I was getting this until I switched to use ssh from https...

before...

https://github.com:myName/myRepo.git

then I ran

`git remote set-url origin git@github.com:myName/myRepo.git`

now fetch works properly

**Comment by lacraig2** [comment]
I am also experiencing the issue @nirodaonline is experiencing. However, I'm just using a normal github repo on a standard port.

**Comment by tfitzpatrickSymplr** [comment]
Same problem with a GitHub repo in GitLens. Any word on a real fix? I can do that credential helper thing, but it should be fixed.

I can pull/push/fetch etc in GitHub desktop or from command line, but it fails through GitLens:
[2022-03-07 19:07:17:607] [c:/_Sites/Codebases/Mainline] Git Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false fetch • bash: /dev/tty: No such device or address • error: failed to execute prompt script (exit code 1) • could not read Username for 'https://github.com': No such file or directory • 475 ms 
[2022-03-07 19:07:17:858] c:\Users\<username>\.vscode\extensions\maattdd.gitless-11.7.1\dist\webpack:\gitless\src\git\shell.ts:190:6
Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false fetch
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No such file or directory

**Comment by eamodio** [comment]
For those who are still experiencing this issue, does running `Git: Fetch` from the command palette work?

**Comment by nirodaonline** [comment]
> For those who are still experiencing this issue, does running `Git: Fetch` from the command palette work?

Hi @eamodio . Thanks for looking into this. 

I just tried `Git: Fetch` from the command palette and it worked (i.e. it asked for the user/password in the GUI)
I also tried from the terminal and it worked. 
I retried from within Gitlens and it did not work: Same error.

**Comment by gonssal** [comment]
@eamodio I just experienced this problem and fixed it by logging out of GitHub and then running `Git: Fetch` from the command palette.

What triggered the problem was mistakenly cancelling the master password popup that sometimes appears when starting VSCode, which probably made the GitHub login fail. This also produced a big problem where the _GITLENS: COMMITS_ panel got stuck at loading, and it cascaded to the rest of the program, making it unusable, even after restarting VSCode.

Hope it helps you debug it.

**Comment by daliusbu** [comment]
After running Git: Fetch on command pallette, I was redirected to webpage with form "GitHub for VS Code is requesting additional permissions" where I pushed a button to "authorize Visual Studio Code" and entered my Github password. All problems dissapeared.
VSCode on Ubuntu.

**Comment by MillerGregor** [comment]
I avoided this by switching my remote from https to ssh:

`git remote set-url origin git@github.com:<org>/<repo>.git`

of course, you'll need to set up ssh keys

**Comment by tachtler** [comment]
Hi,
with GitLens v13.1.1 under Linux, fetching a private Gitlab-Repository via HTTPS, the username will not be promted, only the password, BUT it ends up with following error:
```
[2022-12-10 10:55:28.258] /home/klaus/.vscode-oss/extensions/eamodio.gitlens-13.1.1-universal/dist/gitlens.js:12:8200
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin development:refs/remotes/origin/development
fatal: could not read Username for 'https://[REDACTED]': No such device or address```
```
Is this still a issue?

Thank you in advance!
Klaus.

**Comment by Alejo-Fonseca-Pyxis** [comment]
> > For those who are still experiencing this issue, does running `Git: Fetch` from the command palette work?
> 
> Hi @eamodio . Thanks for looking into this.
> 
> I just tried `Git: Fetch` from the command palette and it worked (i.e. it asked for the user/password in the GUI) I also tried from the terminal and it worked. I retried from within Gitlens and it did not work: Same error.

I did this and it worked. I did a fetch on the default git manager in VS Code and after that I used Git Lents and didn't get the error again.

**Comment by nirodaonline** [comment]
> I did this and it worked. I did a fetch on the default git manager in VS Code and after that I used Git Lents and didn't get the error again.

Did you store your credentials on the disk? Are you working locally or on a remote server?

I can confirm that this issue is still happening on a remote server: The username / password prompt appears when fetching from the command line / command palette , but not via the GitLens fetch button. I get the same error:

`[2022-12-20 14:37:30.877] /home/----------/.vscode-server/extensions/eamodio.gitlens-13.1.1/dist/gitlens.js:12:8200
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch
fatal: could not read Username for 'https://bitbucket.iucn.org': No such device or address`

GitLens v13.1.1

**Comment by d13** [comment]
Resolved with https://github.com/gitkraken/vscode-gitlens/pull/2481

**Comment by nezort11** [comment]
> before...
> 
> https://github.com:myName/myRepo.git
> 
> then I ran
> 
> `git remote set-url origin git@github.com:myName/myRepo.git`
> 

I had to change before:

`https://github.com/Rock-n-block/d-etf`

to

**`https://github.com/Rock-n-block/d-etf.git`**
