### ISSUE TITLE
GitLens v12.0.0 does not work with remote development due to GitKraken Authentication dependency running locally

### ISSUE THREAD

**Issue by traviscrawford** [gitkraken/vscode-gitlens#1840]
The GitLens VSCode plugin now depends on the [GitKraken Authentication](https://marketplace.visualstudio.com/items?itemName=gitkraken.gitkraken-authentication) plugin. When using [VSCode Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) GitLens used to work fine, as GitLens could be installed on the remote development host. "GitKraken Authentication" runs on the local host, which prevents GitLens from loading on the remote host.

[Supporting Remote Development and GitHub Codespaces](https://code.visualstudio.com/api/advanced-topics/remote-extensions) describes how plugins work with remote development. For GitLens to continue functioning for folks using remote development, it would be wonderful if the GitKraken Authentication plugin could be updated to support remote development. A simple fix may allowing it to be installed remotely, just like GitLens can be installed. GitLens and its dependencies must be installed on the same host.

**Comment by mitchelhaan** [comment]
I came looking for the same thing, and it was just resolved (see https://github.com/gitkraken/vscode-gitlens/issues/1836)

**Comment by jaydiablo** [comment]
12.0.0 (the latest release) doesn't seem to solve it for me, downgraded to 11.7.0 to get rid of the notice.

Also using Remote development, and do NOT have GitKraken extension installed.

**Comment by sdykae** [comment]
Same message, with GitKraken extension installed. vscode remote

**Comment by jaydiablo** [comment]
In #1836 it's mentioned that a new release has gone out (which is more recent than when `12.0.0` was tagged here on github), but VS Code still just has `12.0.0` as the latest, so perhaps the fixed version just hasn't published to the marketplace yet.

**Comment by alkatar21** [comment]
As mentioned here https://github.com/gitkraken/vscode-gitlens/issues/1836#issuecomment-1054508599, GitKraken Authentication needs to get an update. This is supposed to be already released according to https://github.com/gitkraken/vscode-gitlens/issues/1836#issuecomment-1054525695, but is not yet in the [marketplace](https://marketplace.visualstudio.com/items?itemName=gitkraken.gitkraken-authentication) for some reason.

**Comment by eamodio** [comment]
Argh, sorry folks there was a CI hiccup that I missed. GitKraken Authentication v1.0.3 with the fix will be in the marketplace very shortly (a couple of minutes).

**Comment by eamodio** [comment]
Duplicate of https://github.com/gitkraken/vscode-gitlens/issues/1836 which will be fixed in a couple of minutes.

**Comment by traviscrawford** [comment]
After upgrading to `GitKraken Authentication v1.0.3` I was able to install both GitLens and GitKraken Authentication on the remote dev env and GitLens now works. Thanks for the prompt fix 🙇
