### ISSUE TITLE
Open Changes action unresponsive in Source Control view

### ISSUE THREAD

**Issue by sibir-ine** [gitkraken/vscode-gitlens#2177]
### Description

1. Open any repo.
2. Navigate to the __Source Control__ view.
3. Navigate to either of the __Commits__ or __Repositories__ sections.
4. Expand a commit.
5. Attempt to view changes made to a file by the commit either by left-clicking a modified file underneath it or by right-clicking it & selecting __Open Changes__ in the context menu.
6. Observe how it can take several seconds or seemingly just fail, requiring multiple attempts.

### GitLens Version

12.2.0

### VS Code Version

Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

### Git Version

git version 2.37.3.windows.1

**Comment by azusachino** [comment]
this problem was so annoying, I think this was the most important function, why??? 
And still no fixes yet, I had to use the old version (but sometimes vscode update extension automatically)

**Comment by Trystanr** [comment]
> this problem was so annoying, I think this was the most important function, why??? And still no fixes yet, I had to use the old version (but sometimes vscode update extension automatically)

Installing version 12.1.2 (VS Code -> Extensions -> Right click GitLens -> Install another version) fixes it temporarily until GitKraken can publish their own fix.

**Comment by eamodio** [comment]
I can't seem to reproduce this -- can you see if you still see it in 12.2.1?

**Comment by sibir-ine** [comment]
No, v12.2.1 works fine. When it fails, I sometimes get an error like this:
> Element with id gitlens:repository(c:/Users/ph/Documents/GitHub/loot/oblivion):branch(sib-tie):root|gitlens:repository(c:/Users/ph/Documents/GitHub/loot/oblivion):commit(918ba67b6c47d00db074446679b1d29f9f8a5ee9) is already registered

**Comment by eamodio** [comment]
Ah, those type of issues should be fixed in 12.2.1 -- thanks!

**Comment by sibir-ine** [comment]
Ah, wait, sorry, I got confused & thought you were talking about the previous version (v12.1.2). It's still occurring with v12.2.1. I got that message while using it.

**Comment by eamodio** [comment]
Hrm, can you restart VS Code and confirm that you are seeing the issue in 12.2.1 (which just went out an ~ hour ago). If so, you provide more steps into what you are seeing? Also, do you have the GitHub or GitLab integration enabled in GitLens?

**Comment by sibir-ine** [comment]
Yes, I just double-checked with v12.2.1 & it's still present. I think the only step that I missed is that I'm opening a workspace with multiple repos. As for integration, I have GH's Pull Requests & Issues extension, is there a setting within GitLens to enable it? I can't seem to find one.

**Comment by sibir-ine** [comment]
I see that when opening a repo from a fresh VS Code window, some repos work fine. However, if I open, e.g., [this one](https://github.com/loot/loot), under the __Repositories__ view, commits in the top-level __Commits__ section don't even expand, & the entire section fails to expand after about a minute. However, commits under other sections (e.g., __Branches__, __Remotes__) do work fine, & so does the __Commit__ view. Not sure if this is related or a separate issue.

**Comment by mje-nz** [comment]
I'm on 12.2.1 using remote SSH, and whenever I try to view file changes I get no response and this is logged:

```
[2022-09-02 14:46:07.305] [renderer3] [error] actual command NOT FOUND: Error: actual command NOT FOUND
	at c._executeContributedCommand (/home/matthew/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/out/vs/workbench/api/node/extensionHostProcess.js:85:63956)
```

**Comment by ChaosEngine** [comment]
Still the same behavior with 12.2.1. Is see 
![image](https://user-images.githubusercontent.com/1271428/188067884-c7b3f004-67e3-4191-8a57-bc1dc57b857d.png)
this and no files in commit - just name of repository directory (?)
Also some error toast is visible.
I use multiple repo project with submodules. In 12.1.X it was working fine with the same setup.

**Comment by dylandifilippo** [comment]
I have the same problem in the 12.2.1 version. I had the problem yesterday with the 12.2.0 version.
I must install Gitlens 12.1.2 to have it to work.
Or if I keep the 12.2.1 version, I must to go to the settings of Gitlens and switch the layout. This fixes the bug but if I restart VS Code, I have to do it each time.

Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:38:59.695Z (2 wks ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.4.0

12.1.2
<img width="534" alt="Gitlens 12 1 2" src="https://user-images.githubusercontent.com/53791026/188141218-cff27f8a-b53d-4447-8957-89e0c0e1afbf.png">

12.2.1 
<img width="532" alt="Gitlens 12 2 1" src="https://user-images.githubusercontent.com/53791026/188141197-09c4f2d2-cca8-4afd-a11d-4df5d82d08bf.png">

**Comment by afriza** [comment]
> 12.2.1

I found a workaround for
- changed/added files under subfolders are not shown
- changed/added files not showing diff when clicked

These are the behavior I observed
1. expand commit
2. now
- changed/added files under subfolders are **not** shown
- changed/added files **not** showing diff when clicked
3. click Refresh
4. now
- changed/added files under subfolders are **shown**
- changed/added files **showing diff** when clicked

**Comment by eamodio** [comment]
I'm really sorry for the issues here. I think I've solved them in the latest GitLens Insiders edition. Can any of you experiencing this problem please verify this fix?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by afriza** [comment]
> You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

I tried 2022.9.518 and no longer have the issues. Tested on COMMITS & REPOSITORIES views

Thanks!

**Comment by sibir-ine** [comment]
I can also confirm that the issue appears to have been fixed in the latest Insiders build. Thanks!

**Comment by eamodio** [comment]
GitLens 12.2.2 has been released with this fix
