### ISSUE TITLE
show current branch only not work in my private repo

### ISSUE THREAD

**Issue by pavlelee** [gitkraken/vscode-gitlens#2533]
### Description

show current branch only not work in my private repo

### GitLens Version

v13.3.1

### VS Code Version

Version: 1.76.0 (Universal)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No

### Git Version

git version 2.31.1

### Logs, Screenshots, Screen Captures, etc

2023-03-02 11:09:55.566 [error] Cannot write private member to an object whose class did not declare it: TypeError: Cannot write private member to an object whose class did not declare it
    at _e (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:108:6338)
    at GraphWebview.asWebviewUri (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:98:162412)
    at f (/root/.vscode-server/extensions/eamodio.gitlens-13.3.1/dist/gitlens.js:1:1160999)
    at GraphWebview.getExcludedRefs (/root/.vscode-server/extensions/eamodio.gitlens-13.3.1/dist/gitlens.js:1:825446)
    at GraphWebview.notifyDidChangeRefsVisibility (/root/.vscode-server/extensions/eamodio.gitlens-13.3.1/dist/gitlens.js:1:820843)
    at GraphWebview.S.<computed> (/root/.vscode-server/extensions/eamodio.gitlens-13.3.1/dist/gitlens.js:1:1254578)
    at GraphWebview.updateIncludeOnlyRefs (/root/.vscode-server/extensions/eamodio.gitlens-13.3.1/dist/gitlens.js:1:832331)
    at /root/.vscode-server/extensions/eamodio.gitlens-13.3.1/dist/gitlens.js:1:809305
    at Pm (/root/.vscode-server/extensions/eamodio.gitlens-13.3.1/dist/gitlens.js:1:788313)
    at GraphWebview.onMessageReceived (/root/.vscode-server/extensions/eamodio.gitlens-13.3.1/dist/gitlens.js:1:809288)
    at GraphWebview.onMessageReceivedCore (/root/.vscode-server/extensions/eamodio.gitlens-13.3.1/dist/gitlens.js:1:792307)
    at GraphWebview.S.<computed> (/root/.vscode-server/extensions/eamodio.gitlens-13.3.1/dist/gitlens.js:1:1254578)
    at f.invoke (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at h.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at l.$onMessage (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:98:165155)
    at c.N (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:106:11223)
    at c.M (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:106:10941)
    at c.H (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:106:10034)
    at c.G (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:106:9172)
    at /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:106:7803
    at f.invoke (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at h.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at p.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
    at /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:122:16556
    at f.invoke (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at h.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at p.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
    at t.E (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:18973)
    at /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:16961
    at f.invoke (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at h.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at u.acceptChunk (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:12638)
    at /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:11925
    at f.invoke (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at h.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at h.u (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:28891)

**Comment by axosoft-ramint** [comment]
Should be fixed in commit: https://github.com/gitkraken/vscode-gitlens/commit/e85bcfd67ba42004e509f538eca5bd288efaad6e

**Comment by axosoft-ramint** [comment]
Can you please verify this fix in tomorrow's pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/199397587-6948b1bc-3019-4d85-a6d5-332fea5d8f78.png)

**Comment by pavlelee** [comment]
@axosoft-ramint The problem still exists.

2023-03-03 12:05:03.162 [error] Cannot write private member to an object whose class did not declare it: TypeError: Cannot write private member to an object whose class did not declare it
    at _e (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:108:6338)
    at GraphWebview.asWebviewUri (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:98:162412)
    at f (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:1151544)
    at GraphWebview.getExcludedRefs (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:813291)
    at GraphWebview.notifyDidChangeRefsVisibility (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:808689)
    at GraphWebview.P.<computed> (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:1245402)
    at GraphWebview.updateIncludeOnlyRefs (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:820144)
    at /root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:797217
    at Om (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:776229)
    at GraphWebview.onMessageReceived (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:797200)
    at GraphWebview.onMessageReceivedCore (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:780223)
    at GraphWebview.P.<computed> (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:1245402)
    at f.invoke (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at h.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at l.$onMessage (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:98:165155)
    at c.N (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:106:11223)
    at c.M (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:106:10941)
    at c.H (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:106:10034)
    at c.G (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:106:9172)
    at /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:106:7803
    at f.invoke (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at h.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at p.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
    at /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:122:16556
    at f.invoke (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at h.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at p.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
    at t.E (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:18973)
    at /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:16961
    at f.invoke (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at h.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at u.acceptChunk (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:12638)
    at /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:11925
    at f.invoke (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at h.fire (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at h.u (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:72:28891)

**Comment by pavlelee** [comment]
@axosoft-ramint switch branch not sync 
<img width="742" alt="image" src="https://user-images.githubusercontent.com/5382358/222629139-844c8fb9-55e2-4499-83b4-67168b6385cb.png">


2023-03-03 12:08:00.095 [error] Cannot write private member to an object whose class did not declare it: TypeError: Cannot write private member to an object whose class did not declare it
    at _e (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:108:6338)
    at GraphWebview.asWebviewUri (/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/api/node/extensionHostProcess.js:98:162412)
    at f (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:1151544)
    at GraphWebview.getExcludedRefs (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:813291)
    at GraphWebview.getState (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:818844)
    at GraphWebview.notifyDidChangeState (/root/.vscode-server/extensions/eamodio.gitlens-2023.3.204/dist/gitlens.js:1:810269)

**Comment by axosoft-ramint** [comment]
@pavlelee Tomorrow's pre-release edition (with this fix) hasn't kicked off yet. It should kick off in roughly four and a half hours, at which point you should see the version number of the pre-release change to `v.2023.3.3xx` (for example, `v2023.3.304`).

![image](https://user-images.githubusercontent.com/67011668/222633377-be4fd740-6b0f-4e09-a8c6-d770edf03f7d.png)

Once it updates, please ensure you are on the latest version (you may need to reload) and let us know if the issue persists.

Thanks!

**Comment by pavlelee** [comment]
It's been solved.

**Comment by axosoft-ramint** [comment]
Glad to hear it, thanks!
