### ISSUE TITLE
full issue ref has escape characters that break hover links

### ISSUE THREAD

**Issue by Jacksondr5** [gitkraken/vscode-gitlens#2625]
### Description

Some context: I'm preparing a repo to be merged into another repo and I'm rewriting commit messages so that the PR references in the hovers will still link back to the original repo.  I _think_ this is possible by changing the references from `#[pr-number]` to `[owner]/[repo]#[pr-number]` based on [this regex](https://github.com/gitkraken/vscode-gitlens/blob/b1f879373c3d190998a1b378d0ddfc90e9a53d89/src/git/remotes/github.ts#L23).  For example: `try a rewritten squash (#3)` -> `try a rewritten squash (Jacksondr5/test-repo#3)`

However, the hover opens a link with encoded backslashes in the repo name: https://github.com/Jacksondr5/test%5C-repo%5C/pull/3 .  This also happens in the owner/org if there is a hyphen in the name.  I've done a little digging and I think the issue is that the text is being escaped before the link is generated.  I'll try to do some more digging later this week.

Is this a valid use case?  Am I doing this the wrong way?

Reproduction steps (already done in [this repo](https://github.com/Jacksondr5/test-repo)):
1. Start with a repo that has a commit history with PR merges in it
2. Rewrite commits using [git-filter-repo](https://github.com/newren/git-filter-repo): `git filter-repo --replace-message replace.txt` 
    - [git-filter-repo manpage](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html) 
    - [replace.txt used in example]()
4. Hover over blame in editor to trigger GitLens hover
5. Click PR reference in commit message

### GitLens Version

13.5.0

### VS Code Version

Version: 1.77.1 (user setup)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:21:11.906Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

### Git Version

git version 2.34.1

### Logs, Screenshots, Screen Captures, etc

Before transformation:
![image](https://user-images.githubusercontent.com/9014034/230736427-aed3720a-c951-4544-8dd9-a63586c54b1a.png)
After transformation:
![image](https://user-images.githubusercontent.com/9014034/230736809-e124b874-95cd-4ae3-b103-340c437d3b32.png)

**Comment by eamodio** [comment]
We believe this issue should be resolved in the latest version of GitLens. Can you please give it a try to confirm that the issue is resolved for you? Thanks!

**Comment by xseignard** [comment]
Hello,
We face the same exact situation as @Jacksondr5 after merging a repo into another.
I tried to update to the last GitLens version, and also tried pre-release and the problem is still there.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2023.10.27xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by xseignard** [comment]
Hello @eamodio 👋 

I just tried with pre release `v2023.11.1504` and the error is still happening 😢  

![Capture d’écran 2023-11-16 à 07 52 17](https://github.com/gitkraken/vscode-gitlens/assets/515603/b41a6535-afde-4b35-ac2e-2b7cee39e9d7)

**Comment by eamodio** [comment]
@xseignard Thanks for the feedback -- there was another issue I found with certain characters in the user/repo name. This should be resolved in tomorrow's (`v2023.11.17xx`) pre-release. Can you try that and see if its fixed for you?

**Comment by xseignard** [comment]
Hello @eamodio 👋 
Sorry for the late reply, but I do confirm it is now fixed.
Thanks for digging 🙏
