### ISSUE TITLE
Shown Contributors commit count differs from shown git shortlog summary

### ISSUE THREAD

**Issue by skwde** [gitkraken/vscode-gitlens#2899]
### Description

The shown `CONTRIBUTORS` commit count in `SOURCE CONTROL` menu differs from the commit count output of `git shortlog --summary --numbered --email`.

### GitLens Version

v14.2.1

### VS Code Version

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z (3 wks ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.6.0

### Git Version

git version 2.41.0

**Comment by eamodio** [comment]
I've fixed a caching issue and ensure that mailmaps are being uses properly in tomorrow's pre-release. But there are also a few toggles that control the _Contributors_ view:

![image](https://github.com/gitkraken/vscode-gitlens/assets/641685/60845d65-d51e-4aba-914d-eebb8b70a8d7)

The new _[Show|Hide] Merge Commits_ (will be in tomorrow's pre-release) and the _View for All Branches_ will control what commits are included in those counts. Which should cause things to match up with `git shortlog`

So please check out tomorrow's (`v2023.12.08xx`) pre-release edition of GitLens, and see if things look good. Thanks!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by skwde** [comment]
@eamodio, I just tested it, but it still doesn't match.

In one of my personal repos I get 1493 commits via `git shortlog` while the contributors tab show 1378.
The toggle 'View for all branches' changes nothing (this repo only has a single branch).
