### ISSUE TITLE
gitlens inspect commit v15+ freezing (The window is not responding)

### ISSUE THREAD

**Issue by elellael** [gitkraken/vscode-gitlens#3470]
### Description

- `gitlens inspect commit details` v15+ seems to freeze when opening big commits
- the previous releases v14.9- do not have this issue
 
**How to reproduce**
 - create a commit with a lot renames (moving 2000+ files into a new folder will do)
 - open gitlens inspect for that commit
 ![image](https://github.com/user-attachments/assets/30c2beff-0402-47a5-91ca-f7ce18d6b55e)
- then it freezes
![image](https://github.com/user-attachments/assets/b4d5de30-2691-42bd-83bc-3bfac7875f33)

### GitLens Version

v15+ has this issue; older releases v14.9- work just fine

### VS Code Version

Version: 1.92.1 (user setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version

git version 2.43.0.windows.1

**Comment by doyee** [comment]
Yes，I met this issue several times，should be a easy reproduce issue.

**Comment by Mattwmaster58** [comment]
I'm running into this a lot with the GitLens Inspect pane. I suspect this has to do with the file I'm inspecting being part of a commit long ago that had thousands of files on it. I have the GitLens (Git) output pane open, but I don't see any specific slow commands, so I suspect this code w/i GitKraken.

Unfortunately I don't have a reliable repro, otherwise I think bisecting would really help here to track this down.

**Comment by Mattwmaster58** [comment]
After looking at this for a while I still am having trouble consistently repro-ing so there's no point in doing a bisect. It definitely seems non-deterministic in my test repo, where I try to trigger it with a git commit that added 10k files, than another git commit that moved those 10k files. Also seems to happen a little more related to window focus being lost?

It seems I see this more often when the window is in the background? Or some background task happens that triggers it, maybe not the inspect details action itself? If someone has a better repro I'd be grateful

Here's a repo that I was able to repro the issue with occasionally: https://github.com/Mattwmaster58/gitlens-3470

**Comment by eamodio** [comment]
@Mattwmaster58 Thank you for the repo! We've now implemented a virtualized renderer for the Commit/Graph Details views so this performance issue should no longer be an issue.

Can you please verify this fix in the latest pre-release edition of GitLens (`v2025.10.07xx` or later)? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by Mattwmaster58** [comment]
~~@eamodio Hmm, still appears to be happening, and like I said, it's hard to get a GOOD repro for this. It occurs after some time of hanging out in the Gitlens Inspect pane, I'm not sure if it's time alone or if window focus changes really do effect it because it's so inconsistent to repro:~~

<img width="1342" height="470" alt="Image" src="https://github.com/user-attachments/assets/16d7709c-ba12-4c3a-8829-f4d68afdea0b" />

retracting my previous comments - maybe some later prerelease cleaned this up, or maybe extensions didn't reload correctly, but it seems fine now.
